- hosts: servers
  become: true
  remote_user: tony
  tasks:
    - name: Update apt repo and cache on all servers
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Install terminator terminal
      apt: 
        name: terminator
        state: present
